require('lazy').setup {
  'NMAC427/guess-indent.nvim',
  -- require 'plugins.notify',
  require 'plugins.autopairs',
  require 'plugins.blink-cmp',
  require 'plugins.conform',
  require 'plugins.debug',
  require 'plugins.gitsigns',
  require 'plugins.indent-line',
  require 'plugins.lint',
  require 'plugins.lspconfig',
  require 'plugins.mini',
  require 'plugins.oil',
  require 'plugins.telescope',
  require 'plugins.todo-comments',
  require 'plugins.treesitter',
  require 'plugins.which-key',
  require 'plugins.markdown-preview',
  -- themes
  -- require 'plugins.themes.tokyonight',
  require 'plugins.themes.catppuccin',
}
